//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreamCommandBooper.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreamCommandBooper.Resources.Localisation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        internal static string Authentication {
            get {
                return ResourceManager.GetString("Authentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Failed, please try again.
        /// </summary>
        internal static string Authentication_Failed {
            get {
                return ResourceManager.GetString("Authentication_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel ID is missing, please log in again.
        /// </summary>
        internal static string Missing_ChannelID {
            get {
                return ResourceManager.GetString("Missing_ChannelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel Name is missing, please log in again.
        /// </summary>
        internal static string Missing_ChannelName {
            get {
                return ResourceManager.GetString("Missing_ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No command lines to process.
        /// </summary>
        internal static string Missing_CommandLines {
            get {
                return ResourceManager.GetString("Missing_CommandLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Channel selected.
        /// </summary>
        internal static string Missing_CurrentChannel {
            get {
                return ResourceManager.GetString("Missing_CurrentChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Item.
        /// </summary>
        internal static string Missing_Item {
            get {
                return ResourceManager.GetString("Missing_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OAuth Token is missing, please log in again.
        /// </summary>
        internal static string Missing_OAuthToken {
            get {
                return ResourceManager.GetString("Missing_OAuthToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests, please wait and try a longer delay.
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many requests.
        /// </summary>
        internal static string TooManyRequests_Title {
            get {
                return ResourceManager.GetString("TooManyRequests_Title", resourceCulture);
            }
        }
    }
}
